name: 서버 동기화
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *' # Everyday at 12am
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 인증서 추가
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: 인증서 신뢰
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: 동기화
        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/html/classplus --delete-after

      - name: API서버 재시작
        #send Ctrl+C to the screen '693817.ClassPlusComcigan'
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "screen -S 693817.ClassPlusComcigan -X stuff $'\003'"
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cp -r /home/ubuntu/html/classplus/api /home/ubuntu"
        #run node.js from '693817.ClassPlusComcigan'
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "screen -dmS 693817.ClassPlusComcigan bash -c 'cd /home/ubuntu/api && node index.js'"